# PIV laboratory scale configuration for validation
project: "digester_piv_validation"

paths:
  case_root: "runs/piv"
  template_root: "case_templates"
  piv_data: "data/raw/piv"
  output_root: "data/processed/piv"

# Lab scale geometry (1:20 scale)
geometry:
  tank:
    L: 1.0   # Length (m) - scaled from 20 m
    W: 0.4   # Width (m) - scaled from 8 m
    H: 0.8   # Height (m) - scaled from 16 m
    
  nozzle:
    count: 8  # Reduced for lab scale
    throat_diameter_mm: 8.0  # Scaled nozzle
    pitch_deg: 45.0
    array: [2, 4]
    start_offset_m: [0.05, 0.05]
    spacing_m: [0.3, 0.09]
    
mesh:
  base_cell_size: 0.01  # Finer mesh for lab scale
  refinement_levels: 2
  wall_layers: 3
  
fluid:
  T: 293.15  # Room temperature (20°C)
  rho: 998.2  # Water at 20°C
  mu: 0.001003  # Water viscosity at 20°C
  nu: 1.004e-6  # Kinematic viscosity
  
operation:
  # Scaled flow using Froude number similarity
  pump_total_m3ph: 2.4  # Scaled from 430 m³/h
  nozzle_flow_m3ph: 0.3  # Per nozzle
  
solver:
  name: "pimpleFoam"
  dt: 0.001  # Smaller timestep for lab scale
  endTime: 60  # 1 minute simulation
  writeInterval: 100
  adjustTimeStep: yes
  maxCo: 1.0
  
# PIV measurement planes
piv_planes:
  - name: "vertical_center"
    type: "xz"
    y: 0.2  # Center width
    window_size: [0.3, 0.3]  # PIV window
    
  - name: "horizontal_mid"
    type: "xy"
    z: 0.4  # Mid height
    window_size: [0.3, 0.3]
    
# PIV processing settings
piv_processing:
  interrogation_window: 32  # pixels
  overlap: 16  # pixels
  search_area: 64  # pixels
  signal_to_noise_threshold: 1.5
  outlier_method: "normalized_median"
  smoothing: true
  
# Validation metrics
validation:
  correlation_threshold: 0.85  # Minimum acceptable correlation
  rmse_threshold_mps: 0.05  # Maximum RMSE
  comparison_regions:
    - name: "jet_region"
      x_range: [0.1, 0.3]
      z_range: [0.2, 0.6]
    - name: "bulk_flow"
      x_range: [0.3, 0.7]
      z_range: [0.3, 0.5]